# Generated by Django 2.2 on 2021-05-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
