# Generated by Django 2.2 on 2021-05-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderlist_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='orderlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Orderlist'),
        ),
    ]
